# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hbu_XLId4Gqw08_UNAFpbayCGyRRYkCV
"""

import streamlit as st
import matplotlib.pyplot as plt
import pickle

# Load the histogram model
with open("histogram_model.pkl", "rb") as f:
    histograms = pickle.load(f)

st.title("Mental Health Data Analysis")

# Select column for visualization
selected_col = st.selectbox("Select a feature:", list(histograms.keys()))

# Plot histogram
counts = histograms[selected_col]["counts"]
bin_edges = histograms[selected_col]["bin_edges"]

fig, ax = plt.subplots()
ax.bar(bin_edges[:-1], counts, width=np.diff(bin_edges), edgecolor="black")
ax.set_xlabel(selected_col)
ax.set_ylabel("Frequency")
ax.set_title(f"Histogram of {selected_col}")

st.pyplot(fig)